---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homelab.server.io
  resources:
  - resourcequotaconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homelab.server.io
  resources:
  - resourcequotaconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - homelab.server.io
  resources:
  - resourcequotaconfigs/status
  verbs:
  - get
  - patch
  - update
