apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: homelab-catalog
  namespace: homelab-operators
spec:
  sourceType: grpc
  image: docker.io/kallepan/homelab-catalog:0.0.1
  displayName: Homelab Catalog
  publisher: Kajeepan Kandeepan
  updateStrategy:
    registryPoll:
      interval: 30m