---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq-operator-serviceaccount
  namespace: homelab-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rq-operator-role
  namespace: homelab-operators
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rq-operator-rolebinding
roleRef:
  kind: Role
  name: rq-operator-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rq-operator-sa
  namespace: homelab-operators