---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-homelab-server-io-v1alpha1-resourcequotaconfig
  failurePolicy: Fail
  name: mresourcequotaconfig.kb.io
  rules:
  - apiGroups:
    - homelab.server.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcequotaconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-homelab-server-io-v1alpha1-resourcequotaconfig
  failurePolicy: Fail
  name: vresourcequotaconfig.kb.io
  rules:
  - apiGroups:
    - homelab.server.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcequotaconfigs
  sideEffects: None
