apiVersion: homelab.server.home/v1alpha1
kind: ResourceQuotaConfig
metadata:
  labels:
    app.kubernetes.io/name: resourcequotaconfig
    app.kubernetes.io/instance: resourcequotaconfig-sample
    app.kubernetes.io/part-of: homelab-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: homelab-operator
  name: resourcequotaconfig-sample
spec:
  # TODO(user): Add fields here
